[versions]
postgresql = "42.7.4"
springframework-devtools = "3.3.5"
springframework-jpa = "3.3.5"
springframework-security = "3.3.5"
springframework-test = "3.3.5"
springframework-web = "3.3.5"
springframework-configuration-processor = "3.3.5"
springframework-security-test = "6.3.4"
lombok = "1.18.34"
spring-boot = "3.3.5"
spring-dependency-management = "1.1.6"
graalvm-buildtools-native = "0.10.2"

[libraries]
postgresql = { module = "org.postgresql:postgresql", version.ref = "postgresql" }
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok" }
springframework-devtools = { module = "org.springframework.boot:spring-boot-devtools", version.ref = "springframework-devtools" }
springframework-configuration-processor = { module = "org.springframework.boot:spring-boot-configuration-processor", version.ref = "springframework-configuration-processor" }
springframework-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa", version.ref = "springframework-jpa" }
springframework-security = { module = "org.springframework.boot:spring-boot-starter-security", version.ref = "springframework-security" }
springframework-test = { module = "org.springframework.boot:spring-boot-starter-test", version.ref = "springframework-test" }
springframework-web = { module = "org.springframework.boot:spring-boot-starter-web", version.ref = "springframework-web" }
springframework-security-test = { module = "org.springframework.security:spring-security-test", version.ref = "springframework-security-test" }

[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
spring-dependency-management = { id = "io.spring.dependency-management", version.ref = "spring-dependency-management" }
graalvm-buildtools-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-buildtools-native" }